### ISSUE TITLE
Doesn't work with `quant-ph` in the link.

### ISSUE THREAD

**Issue by we-taper** [ssp/arXivToBibTeX#10]
When I tried to retrieve information for the article <https://arxiv.org/abs/quant-ph/0304179>, the website gave the result of another article in the `math` category:

```
@misc{math/0304179,
Author = {Sean Sather-Wagstaff},
Title = {Complete intersection dimension for complexes},
Year = {2003},
Eprint = {arXiv:math/0304179},
}
```

Similar bugs were found for links like: `https://arxiv.org/abs/quant-ph/*some numbers*`.

**Comment by ssp** [comment]
Thanks for letting me know @we-taper .

The issue should be fixed now.
