### ISSUE TITLE
HTML and wiki settings omit the last author

### ISSUE THREAD

**Issue by ampolloreno** [ssp/arXivToBibTeX#12]
It looks like the HTML and wiki setting omit the last author - e.g. for 2005.00897:
the bibtex entry gives:

Author = {Timothy P. McKenna and Jeremy D. Witmer and Rishi N. Patel and Wentao Jiang and Raphaël Van Laer and Patricio Arrangoiz-Arriola and E. Alex Wollack and Jason F. Herrmann and Amir H. Safavi-Naeini}

But the HTML button gives:
Timothy P. McKenna, Jeremy D. Witmer, Rishi N. Patel, Wentao Jiang, Raphaël Van Laer, Patricio Arrangoiz-Arriola, E. Alex Wollack, Jason F. Herrmann

and the Wiki entry gives:
Timothy P. McKenna, Jeremy D. Witmer, Rishi N. Patel, Wentao Jiang, Raphaël Van Laer, Patricio Arrangoiz-Arriola, E. Alex Wollack, Jason F. Herrmann.

**Comment by ssp** [comment]
Thanks for uncovering this bug and already finding its cause @ampolloreno !
