### ISSUE TITLE
BibLaTeX output

### ISSUE THREAD

**Issue by pbelmans** [ssp/arXivToBibTeX#3]
It might be interesting to also output BibLaTeX code, which has better support for preprints. The output for the [suggested example](https://arxiv2bibtex.org/?q=1510.01797&format=bibtex) would be

```
@online{1510.01797,
  author = {Hans-E. Porst and Ross Street},
  title = {Generalizations of the Sweedler dual},
  year = {2015},
  eprint = {1510.01797},
  eprinttype = {arxiv},
  eprintclass = {math.CT},  
}
```

The fun thing about this is that it is then possible to let your backend automatically create links to the abstract page (or the pdf if you like).

**Comment by ssp** [comment]
Interesting idea @pbelmans, I added that format.

As I am not using BibLaTeX myself at the moment, please check the site to see whether the result works as intended. Thanks!

**Comment by pbelmans** [comment]
Thanks!

There is also the `eprintclass` field that is recognized by BibLaTeX.
