### ISSUE TITLE
Plaintext output

### ISSUE THREAD

**Issue by pbelmans** [ssp/arXivToBibTeX#5]
It might be interesting to have an API returning plaintext. This would be useful if you want to automatically generated BibTeX files by running an external script scraping `.aux` for arXiv-like citations, and then writing the appropriate output to a BibTeX file.

**Comment by ssp** [comment]
I have currently no plans to add this feature. I also think that people who script themselves in this way may be better off using the arXiv API directly.

But I ensure output is valid XML now so you can use an XPath to extract the information this way. E.g.

`xmllint --xpath "//div[@id='bibtex']/textarea/text()" output.xml`
