### ISSUE TITLE
Accept URLs in the main input field

### ISSUE THREAD

**Issue by a3nm** [ssp/arXivToBibTeX#7]
Hello,

Thanks for the https://arxiv2bibtex.org service! When using it, it's natural for me to paste in the search box the URL of an arXiv page, e.g., "https://arxiv.org/abs/1701.04626". The system doesn't understand this. So I just thought a nice feature would be to support URLs (and find the identifier there).

**Comment by ssp** [comment]
Thanks for the suggestion @a3nm – I added that feature just now.

**Comment by a3nm** [comment]
Works fine for me, thanks a lot!

**Comment by a3nm** [comment]
Actually, just coming back to point out a small problem: it does not work for URLs with a specific version indicated, e.g., "https://arxiv.org/abs/1411.1995v3", whereas "1411.1995v3" works fine. Would it be possible to fix this too? Thanks a lot!

**Comment by ssp** [comment]
@a3nm sorry for not seeing your remark for so long.

Thanks for the nice idea, I added it now.

**Comment by a3nm** [comment]
No worries, thanks for adding! That said, I see that the version suffix is stripped in the generated citation. I'm not sure that this is the best behavior; what if the user wants to cite specifically this version?

In fact, I don't know what is the best practice here: should people be encouraged to cite a specific version of an article or not? Personally I tend to cite specific versions, because I don't want, e.g., that references to a specific section/result/etc. stop working if the cited article is updated...

**Comment by ssp** [comment]
@a3nm I briefly considered taking into account the version but that seems non-trivial as the intent of the user is unclear. I don’t know the best practice either so I decided to stick with the existing one.

**Comment by a3nm** [comment]
I see. Maybe it would make sense to produce outputs for the two situations, e.g., "If you want to cite this specific version", vs "If you want to cite any version of this paper". In any case, it makes sense to follow the existing behavior. Thanks for fixing!
