### ISSUE TITLE
API to resolve an arXiv URL to BibTeX

### ISSUE THREAD

**Issue by sjackman** [ssp/arXivToBibTeX#8]
A DOI URL may be resolved to BibTeX like so:
```sh
curl -sLH "Accept: text/bibliography; style=bibtex" "https://doi.org/10.1101/071282"
```

Is there a similar API for resolving an arXiv URL? The following for example returns XML rather than BibTeX.
```sh
curl -sLH "Accept: text/bibliography; style=bibtex" "http://export.arxiv.org/api/query?search_query=1708.01492"
```

**Comment by ssp** [comment]
@sjackman : To the best of my knowledge arXiv does not support BibTeX output at the moment. That’s why arXiVToBibTeX has to create its own.

I am wondering whether this can be realized as an additional output format for arXivToBibTeX.

**Comment by ssp** [comment]
@sjackman: I gave this a shot. You can try adding the parameter 

outputformat=raw 

to an arXiv2bibTeX URL to get just the bibliographic data without the web page.

**Comment by sjackman** [comment]
Works like a charm! Thanks!
https://arxiv2bibtex.org/?q=1708.01492&outputformat=raw

**Comment by sjackman** [comment]
```sh
# Convert arXiv to bibtex.
arxiv()
{
	for i do; curl -s "https://arxiv2bibtex.org/?outputformat=raw&q=$i" | paste -sd' ' - | sed 's/}, }/}}/'; done
}
```
https://github.com/sjackman/dotfiles/blob/9a6e15e89e67e8cab90c2b6479015f102921d50c/.functions#L92-L96
